name: Docker

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1.1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
