name: Tests

on:
  push:
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.10", "3.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Install package
        run: poetry install
      - name: Run tests
        run: sudo $(poetry env info -p)/bin/pytest --cov=fast_mda_traceroute --cov-report=xml
      - uses: codecov/codecov-action@v2

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}

  pypi:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-python-action@v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          upload: ${{ startsWith(github.ref, 'refs/tags/v') }}
